environment:
  CODECAKEBUILDER_SECRET_KEY:
    secure: 8VAzdXgUQaJyFoU3WLf2iPFV/8zPDm9qV4TfOpx8/rg=
  SqlServer/MasterConnectionString: Server=(local)\SQL2017;Database=master;User ID=sa;Password=Password12!
  API_KEY_TO_PUSH_NPM_PACKAGES:
    secure: ABYojwv0/UimKKf8vhsD2UlHeqm25UMSwav+rFU3d0R3DTLRq+gXbMftWieRXya1hnJbkzgLf6evzxGEtSQ9WUhCyphEO2i0pNEfHEdYceSWTbWBiDu0v2/39Rw3hQS0kdb3bNMknI/BhLv1vNg+WQ==
services: mssql2017
version: build{build}
image: Visual Studio 2022
clone_folder: C:\CKli-World\CK-Core-Projects\CK-SqlServer-Dapper
test: false
on_finish:
- ps: Get-ChildItem -Recurse *.log -exclude LastRun.log  -ErrorAction SilentlyContinue | % { Push-AppveyorArtifact $_.FullName }
init:
- git config --global core.autocrlf true
build_script:
- dotnet run --project CodeCakeBuilder -nointeraction
